services:
  - type: web
    name: eduxo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
